### ISSUE TITLE
Log message formatting

### ISSUE THREAD

**Issue by maikg** [nesquena/dante#3]
I might be missing something very obvious here, but would it be possible to add some kind of configuration option to alter the default log output for Dante's own messages? I currently work around this by redefining the `log` method inside the `Dante::Runner` class like so:

``` ruby
module Dante
  class Runner
    def log(message)
      puts "[#{Time.now}] #{message}"
    end
  end
end
```

I could add an option to `Runner` class that takes a proc or a lambda that would be responsible for formatting the default log output. The default value for this option would simply `puts` the message like the current implementation for `log` does. Would that solution work for you?

In addition, it might be helpful to expose the `log` method on the `Dante` module so daemon implementations can also make use of the same formatting. Any opinion or suggestions on that?

**Comment by krainboltgreene** [comment]
We should really just use the stdlib logger, it's much better.

I should be able to call `Dante.logger.info("Foo")`

**Comment by nesquena** [comment]
Yeah that's a good point, I agree that might make more sense.

**Comment by krainboltgreene** [comment]
Moved to new repository libdante/dante.gem/issues/2.
