### ISSUE TITLE
Dante and command line arguments

### ISSUE THREAD

**Issue by neomantic-zz** [nesquena/dante#4]
Dante is pretty nice.  I tried to use the classes in a project of mine, not as a CLI daemon, but as a in process daemon - (The use case, was spawning a service, inside of cucumber).   It works perfectly with one exception.

But I encountered what I consider a problem.  When a runner is executed , Dante uses the OptionParser.  Of course, the OptionParser, uses ARGV.   So when someone uses Dante in the code, rather than from the CLI, it is possible to pass arguments to Dante, that Dante does not understand.

Maybe you only want to use Dante from the CLI, but it works pretty well in the code too.  There is no similar code in daemon_spawn, or Daemons, that does what Dante can do in this regard.

**Comment by krainboltgreene** [comment]
Moved to new repository libdante/dante.gem/issues/3
