### ISSUE TITLE
Use standard logger

### ISSUE THREAD

**Issue by nesquena** [nesquena/dante#8]
From @krainboltgreene 

> We should really just use the stdlib logger, it's much better.
> I should be able to call Dante.logger.info("Foo")

Totally agree, want to leave this as a reminder.

**Comment by krainboltgreene** [comment]
So I set out to actually make the modification required, but I've run into a situation where I want to mock the logger for testing, but I really dislike mocha.

If I switched over to rspec, but retained coverage, would you hate me? :p

**Comment by krainboltgreene** [comment]
Moved to new repository: libdante/dante.gem/issues/2
